apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x83359uuk-dotnet-basic
  janus-idp.io/tekton: x83359uuk-dotnet-basic
  backstage.io/kubernetes-id: x83359uuk-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x83359uuk-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
